schema_version = "1.0.0"
id = "ConvertToGaming"
version = "1.0.0"
name = "Convert To Gaming"
tagline = "Convert To Gaming"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Convert-to-gaming"
tags = ["Objects"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]