schema_version = "1.0.0"
id = "bb_Covert to gaming"
version = "1.0.0"
name = "BB UVs"
tagline = "Convert quad model for gaming"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Convert-to-gaming"
tags = ["Mesh", "UV"]
blender_version_min = "4.5.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]
